config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :scans, only: [:new, :create]
  get 'aboutus', to: 'pages#aboutus'
  root to: 'pages#home'

  resources :products, only: %i[index show], shallow: true do
    resources :feedbacks, only: %i[create show]
  end

  resources :favorites, only: %i[index create destroy]
end

app/views/pages/aboutus.html.erb
<%= render "/shared/header" %>
<%= render "/shared/clickable-avatar" %>

<div class="aboutus-container">

  <div class ="aboutus-vision">
    <h1 style="white-space: nowrap;">Our vision</h1>
    <%= cl_image_tag "IMG_9907_hqpxid", height: 1500, :radius=>100 %>
    <p> <strong>Welcome on board ! </strong> Wear fights for
     more sustainable and ethical fashion. Our mission is to
     give you the keys to better consume and let you discover ecofriendly brands of tomorrow.
     So are you ready to join of our <strong>green fashion ecosystem</strong>?</p>
    </div>

  <div class ="aboutus-notation">

      <h1 style="white-space: nowrap;">What is Wear notation ?</h1>
      <div id="accordion">
        <ul class="list-group list-group-flush">
            <div class="card-product-description-container card-environnement" id="headingOne">
              <button class="btn btn-link card-product-description-container" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <li class="list-criteria"><i class="fab fa-envira"></i> Environment: mark/100</li>
              </button>
            </div>

            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body-criteria">
                <p>The environmental criterion accounts for the proper management of waste along the chain, the use of materials, or the consumption of water generated point.</p>
              </div>
            </div>

            <div class="card-product-description-container card-environnement" id="headingTwo">
                <button class="btn btn-link card-product-description-container" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                  <li class="list-criteria"><i class="fas fa-people-carry"></i> Labor: mark/100</li>
                </button>
            </div>

            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card-body-criteria">
                <p>The Labor criterion takes into account the knowledge of the sector, the relationship between suppliers, and takes into account the well-being of employees in their daily work.</p>
              </div>
            </div>

            <div class="card-product-description-container card-environnement" id="headingThree">
              <button class="btn btn-link card-product-description-container" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                <li class="list-criteria"><i class="fas fa-paw"></i> Animal: mark/100</li>
              </button>
            </div>

            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
              <div class="card-body-criteria">
                <p>The animal criterion takes into account the knowledge of the industry, the relationship between suppliers, and takes into account the well-being of employees in their daily work.</p>
              </div>
            </div>

            <div class="card-product-description-container card-environnement" id="headingFour">
              <button class="btn btn-link card-product-description-container" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                <li class="list-criteria"><i class="fas fa-recycle"></i> Composition: mark/100</li>
              </button>
            </div>

            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
              <div class="card-body-criteria">
                  The composition criterion accounts for the materials used (recycled, organic, untreated), the place of manufacture, or the production process.
              </div>
            </div>
        </ul>
      </div>
  </div>

  <div class="aboutus-button">
    <%= link_to "Join us", products_path, class: "btn-light-green"%>
  </div>

</div>

app/views/pages/home.html.erb
<div>
  <%= render "/shared/clickable-avatar" %>
</div>

<div class="main-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url('<%= cl_image_path "homepage_background_lbfwxz", height: 1500, crop: :fill %>')">
    <h1> Wear </h1>
    <h2>Say stop to fast fashion and join the Wear family </h2>
    <% unless user_signed_in?%>
      <%= link_to "See the products","products", id: "button-call-to-action" %>
    <% end %>
    <% if user_signed_in?%>
      <div class="searchbar-home" id="seachbar-home">
        <%= simple_form_for :products_filter, url: products_path, method: :get do |f| %>
          <%= f.input :query, label: false, required: false, placeholder: "Search for a product", style: "width: 350px" %>
          <div class="button-space">
            <%= submit_tag "Search", class: "btn-light-green"%>
          </div>
        <% end %>
      </div>
    <% end %>
    <a href="#articles-list">
      <i class="fas fa-chevron-down"></i>
    </a>
  </div>

  <div class="articles" id="articles-list">
    <h2>Weekly News</h2>
    <div class="card mb-4">
      <img class="card-img-top" src="https://cdn.shopify.com/s/files/1/0061/7562/1187/files/sam-carter-GHOiyov2TSQ-unsplash_grande.jpg?v=1583782238" alt="Card image cap">
      <div class="card-body">
        <h3 class="card-title">What's behind organic wool ?</h3>
        <p class="card-text">Wool is natural fibre that has inherent characteristics that make it renewable and biodegradable. That is true with all woollen products ...</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card mb-4">
      <img class="card-img-top" src="https://www.surfmadame.com/wp-content/uploads/2017/05/CottonFarmer-1-e1493657415837-1090x728.jpg">
      <div class="card-body">
        <h3 class="card-title">Who is behind your outfit ?</h3>
        <p class="card-text">
          Garment workers around the world make everything from luxury handbags to fast fashion leggings. Here are some of their stories ... </p>
        <p class="card-text"><small class="text-muted">Last updated 2 days ago</small></p>
      </div>
    </div>
    <div class="card mb-4">
      <img class="card-img-top" src="https://www.dmarge.com/wp-content/uploads/2016/04/green-suit-1.jpg" alt="Card image cap">
      <div class="card-body">
        <h3 class="card-title">What is a green outfit ?</h3>
        <p class="card-text">
          Eco-fashion is any brand or line that attempts to minimize the impact on the environment, and often the health of the consumers and the working conditions for the people that are making the clothes ... </p>
        <p class="card-text"><small class="text-muted">Last updated 3 days ago</small></p>
      </div>
    </div>
    <div class="card mb-4">
      <img class="card-img-top" src="https://fashionunited.fr/XFk_iaFm0zWMv92ZkdRKiUU0AA74IHiu9ipNqZhfcsI/resize:fill:694:391:1/gravity:sm/quality:70/aHR0cHM6Ly9zdGF0aWMuZmFzaGlvbnVuaXRlZC5jb20vMjAyMDA2LzR2ZWpheGRhcndpbjEuanBn" alt="Card image cap">
      <div class="card-body">
        <h3 class="card-title"> Veja x Darwin - Concept Store </h3>
        <p class="card-text">
          VEJA has chosen this hybrid place to launch its new project: a space to clean, repair and recycle your old pairs ... </p>
        <p class="card-text"><small class="text-muted">Last updated 5 days ago</small></p>
      </div>
    </div>
    <h2><%= link_to "About Us", aboutus_path, id:"aboutus-header" %></h2>
    <div class="card mb-4">
      <img class="card-img-top"<%= cl_image_tag "IMG_9907_hqpxid"%>
    </div>
  </div>
</div>