config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :scans, only: [:new, :create]
  get 'aboutus', to: 'pages#aboutus'
  root to: 'pages#home'

  resources :products, only: %i[index show], shallow: true do
    resources :feedbacks, only: %i[create show]
  end

  resources :favorites, only: %i[index create destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  before_validation :strip_blanks

  # Picture from cloudinary
  has_one_attached :picture

  # brands
  belongs_to :brand

  # feedbacks
  has_many :feedbacks, dependent: :destroy

  # favorites
  has_many :favorites, dependent: :destroy

  # validation
  validates :name, presence: true, uniqueness: { scope: :brand_id, message: "this product for this brand already exists" }
  validates :description, length: { minimum: 6, message: "description must be at least 6 character-long" }
  validates :environment, presence: true,
                          numericality: { only_integer: true, message: "must be an integer between 0 and 100" },
                          inclusion: { in: (0..100), message: "must be an integer between 0 and 100" }
  validates :labor, presence: true,
                    numericality: { only_integer: true, message: "must be an integer between 0 and 100" },
                    inclusion: { in: (0..100), message: "must be an integer between 0 and 100" }
  validates :animal, presence: true,
                     numericality: { only_integer: true, message: "must be an integer between 0 and 100" },
                     inclusion: { in: (0..100), message: "must be an integer between 0 and 100" }
  validates :composition, presence: true,
                          numericality: { only_integer: true, message: "must be an integer between 0 and 100" },
                          inclusion: { in: (0..100), message: "must be an integer between 0 and 100" }

  validates :gender, inclusion: {in: ['Woman', 'Man']}

  def favorite?(user)
    Favorite.find_by(user: user, product: self)
  end

  def quality_color(number)
    case number
    when 80..100
      return "#AAD576"
    when 60..79
      return "#FFD670"
    when 40..59
      return "#F4A259"
    else
      return "#ee6055"
    end
  end

  private

  def strip_blanks
    self.name = name.strip
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if params[:query].present?
      @products = Product.where("title ILIKE ?", "%#{params[:query]}%")
    end
    if params[:products_filter].present?
      if params[:products_filter][:query].present?
        sql_query = "category ILIKE :query OR description ILIKE :query"
        @products = Product.where(sql_query, query: "%#{params[:products_filter][:query]}%") unless params[:products_filter][:query].empty?
      end

      if params[:products_filter][:gender].present?
        @products = @products.where(gender: params[:products_filter][:gender]) unless params[:products_filter][:gender].empty?
      end

      if params[:products_filter][:category].present?
        @products = @products.where(category: params[:products_filter][:category]) unless params[:products_filter][:category].empty?
      end

      if params[:products_filter][:average_rating].present?
        found_products = []
        @products.each do |product|
          average_rating = (product.environment + product.labor + product.animal + product.composition) / 4
          found_products << product if average_rating >= params[:products_filter][:average_rating].to_i
        end
        @products = found_products
      end
    end
  end

  def show
    @feedback = Feedback.new
    @product = Product.find(params[:id])
    @brands = Brand.all
    @markers = @brands.geocoded.map do |brand|
      {
        lat: brand.latitude,
        lng: brand.longitude,
        info_window: render_to_string(partial: "info_window", locals: { brand: brand }),
      }
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :picture, :environment,
                                    :environement_details, :labor, :labor_details, :animal,
                                    :animals_details, :composition, :composition_details)
  end
end

app/views/products/_card.html.erb
<div class="card-product">
  <%= link_to product_path(product) do %>
    <% if product.picture.attached? %>
      <%= cl_image_tag (product.picture.key), class: "card-product-img"%>
    <% end %>
    <% if product.favorite?(current_user) %>
      <%= link_to favorite_path(product.favorite?(current_user), from: "products"), method: :delete, remote: true do  %>
        <i class="fas fa-heart"></i>
      <% end %>
    <% else %>
      <%= link_to favorites_path(product: product), method: :post, remote: true do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% end %>
    <div class="card-product-description-container">
      <p class="card-product-title"> <%=  link_to "#{product.name}", product_path(product) %> </p>
      <div class="card-product-description trait_below">
        <p> <%= product.brand.name %></p>
        <% average_rating = (product.environment + product.labor + product.animal + product.composition) / 4 %>
        <p class="product-score"> <i class="fas fa-leaf"> </i> <%= average_rating %>/100 </p>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_info_window.html.erb
<h2><%= brand.name %></h2>
<p><%= brand.address %></p>

app/views/products/index.html.erb
<%= render "/shared/header" %>
<%= render "/shared/clickable-avatar" %>

<div class="main-container">

  <div class="searchbar-home">
    <%= simple_form_for :products_filter, url: products_path, method: :get do |f| %>
    <%= f.input :query, label: false, required: false, placeholder: "Search for a product", style: "width: 350px", input_html: { class: "no-focus-border"} %>
    <div class="search-filter">
      <%= f.input :gender, label: false, prompt: "Gender", collection: Product.pluck(:gender).uniq, required: false%>
      <%= f.input :category, label: false, prompt: "Category", collection: Product.pluck(:category).uniq, required: false %>
    </div>
    <div class="filter-rating">
      <div id="slider-value">0</div>
      <%= f.input :average_rating, as: :range, required: false, label: "Sustainability Score", input_html: {value: '0'} %>
      <div class="button-space">
        <%= submit_tag "Search", class: "btn-light-green"%>
        <% end %>
      </div>
    </div>
  </div>
  <ul class="container-product">
    <% @products.each do |product|%>
      <div id="product-card-<%= product.id  %>">
        <%= render 'card', product: product %>
      </div>
    <% end %>
  </ul>
</div>

app/views/products/show.html.erb
<%= render "/shared/header" %>
<%= render "/shared/clickable-avatar" %>
<div class="products-container">
  <div class="card-show">
  <% if @product.picture.attached? %>
    <%= cl_image_tag(@product.picture.key, width: 370, height: 300, crop: :fill) %>
  <% end %>
  <div class="card-body">
    <h2 class="card-title"><%= @product.name %></h2>
    <p class="card-text"><%= @product.description %></p>
  </div>

  <div id="accordion">
    <ul class="list-group list-group-flush">
          <button class="btn btn-link card-product-description-container heading" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style="background-color:<%= @product.quality_color(@product.environment) %>;max-width: <%= @product.environment %>%;">
            <li class="list-criteria">
              <i class="fab fa-envira"></i> Environment: <%= @product.environment %>/100
              <i class="fas fa-chevron-down" id="list-chevron"></i>
            </li>
          </button>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body-criteria">
            <p>The environmental criterion accounts for :</p>
            <ul>
              <li>The proper management of waste along the chain</li>
              <li>The water and energy consumption management</li>
              <li>The carbon footprint</li>
            </ul>
          </div>
        </div>

        <button class="btn btn-link card-product-description-container heading" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo" style="background-color:<%= @product.quality_color(@product.labor) %>;max-width: <%= @product.labor %>%;">
          <li class="list-criteria"><i class="fas fa-people-carry">
            </i> Labor: <%= @product.labor %>/100
            <i class="fas fa-chevron-down" id="list-chevron"></i>
          </li>
        </button>

        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body-criteria">
            <p>The Labor criterion takes into account :</p>
            <ul>
              <li>The proper management of waste along the chain</li>
              <li>The water and energy consumption management</li>
              <li>The carbon footprint</li>
            </ul>
          </div>
        </div>

        <button class="btn btn-link card-product-description-container heading" id="headingThree" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree" style="background-color:<%= @product.quality_color(@product.animal) %>;max-width: <%= @product.animal %>%;">
          <li class="list-criteria"><i class="fas fa-paw">
            </i> Animal: <%= @product.animal %>/100
            <i class="fas fa-chevron-down" id="list-chevron"></i>
          </li>
        </button>

        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
          <div class="card-body-criteria">
            <p>The animal criterion takes into account :</p>
            <ul>
              <li>The use of animals or use of alternative materials</li>
              <li>The animals treatment and suffering</li>
            </ul>

          </div>
        </div>

        <button class="btn btn-link card-product-description-container heading" id="headingFour" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour" style="background-color:<%= @product.quality_color(@product.composition) %>;max-width: <%= @product.composition %>%;">
          <li class="list-criteria"><i class="fas fa-recycle">
            </i> Composition: <%= @product.composition %>/100
            <i class="fas fa-chevron-down" id="list-chevron"></i>
          </li>
        </button>

        <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
          <div class="card-body-criteria">
            <p>The composition criterion accounts mostly for the materials used and if they are :</p>
            <ul>
              <li>Recycled/non recycled</li>
              <li>Organic/non-organic</li>
              <li>Treated/untreated</li>
            </ul>
          </div>
        </div>
      </div>
    </ul>
    <div class="card-btn-product-show">
      <a href="/" class="btn-show">Buy on Website</a>
      <a href="#map" class="btn-show">Search your shop</a>
  </div>
  </div>

  <div data-controller="insert-in-list">
    <div data-insert-in-list-target="items">
      <div id="feedbacks-list">
        <h2>Feedbacks</h2>
        <a href="#leave-feedback"> Write a feedback
        <i class="fas fa-plus-circle"></i>
        </a>
      </div>
      <div id="feedback-container">
        <% if @product.feedbacks.blank? %>
          <p> <em>Be the first to leave a feedback ! </em></p>
        <% else %>
        <% @product.feedbacks.order(created_at: :desc).each do |feedback|%>
          <%=render "feedbacks/feedback", feedback: feedback %>
        <% end %>
      <% end %>
        </div>
    </div>
  </div>
  <div class="form-feedback" id="leave-feedback">
    <h2>Leave a feedback</h2>
    <%= simple_form_for([@product, @feedback], remote: true) do |f| %>
      <%= f.label :purchase_date, 'Purchase date' %> <br>
      <%= f.input_field :purchase_date, as: :date, html5: true, required: true %>
      <%= f.input :comment, as: :text, input_html: {style:  'height:80px;', rows: 2}, placeholder: "Tell us what you like/dislike about your product" %>
      <%= f.label :picture_worn, "Upload a picture of your product" %> <br>
      <%= f.input_field :picture_worn, as: :file%>
      <div class='submit-review-btn'>
        <%= f.submit "Submit feedback", class:"btn-light-green" %>
      </div>
    <% end %>
  </div>
  <div id="map"
     style="width: 100%; height: 400px; margin: auto; margin-top: 5px; border-radius: 5px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>